name: Build kubeops-ng project

on:
  push:
    branches:
      - develop
env:
  IMAGE_NAME: kubeops-ng-app
  REPO_OWNER_LOWERCASE: 'kubesuperops'
  REGISTRY: 'kubesuperops.azurecr.io'

jobs:
  build-kubeops-ng:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Login acr
        uses: docker/login-action@v1
        if: endsWith(github.ref, '/develop') || endsWith(github.ref, '/staging') || endsWith(github.ref, '/master')
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}

      - name: Install GitVersion
        uses: gittools/actions/gitversion/setup@v0.9.10
        with:
          versionSpec: '5.x'

      - name: Execute GitVersion
        uses: gittools/actions/gitversion/execute@v0.9.10
        with:
          useConfigFile: true
          targetPath: ./kubeops-ng
          configFilePath: ./kubeops-ng/GitVersion.yml

      - name: Display SemVer
        run: |
          echo "SemVer: $GITVERSION_SEMVER"

      # ============= ENC Login Container registry and init git semver ==========
      # ============= Build and puch to registry ================================
      - name: Build and push to registry
        run: |
          cd kubeops-ng
          docker build -t ${{ env.REGISTRY }}/${{ env.REPO_OWNER_LOWERCASE }}/${{ env.IMAGE_NAME }}:$GITVERSION_SEMVER \
                       -t ${{ env.REGISTRY }}/${{ env.REPO_OWNER_LOWERCASE }}/${{ env.IMAGE_NAME }}:latest \
                       --build-arg build_env=${{ env.ENVIRONMENT }} .
          docker push -a ${{ env.REGISTRY }}/${{ env.REPO_OWNER_LOWERCASE }}/${{ env.IMAGE_NAME }}
      # ============== End Build =================================================
      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: ${{ env.REGISTRY }}/${{ env.REPO_OWNER_LOWERCASE }}/${{ env.IMAGE_NAME }}:latest
          format: 'table'
          exit-code: '1'
          ignore-unfixed: true
          vuln-type: 'os,library'
          severity: 'CRITICAL,HIGH'
